# Generated by Django 2.0.1 on 2018-01-28 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='added_ad',
            new_name='added_at',
        ),
    ]
